### ISSUE TITLE
How to install linux release? 

### ISSUE THREAD

**Issue by daniel-westcott** [tnrich/ove-electron#3]
I'm excited to use the editor, but I don't know how to install it. Sorry to be so daft.

**Comment by tnrich** [comment]
Hey @daniel-wescott, 
Glad you're excited to use it. I am not totally sure how to install it because I haven't actually used a Linux machine much.  

I think the general idea is to go to this repo's release page and download the Linux release. Maybe try double clicking the downloaded file?

Maybe @beeltetun could help us out with some more specifics on how he went about installing it on Linux?

I can ask some other co-workers on how the install should go

**Comment by beeltetun** [comment]
Hi,

download the file and open a terminal. Then

`chmod +x Open-Vector-Editor-0.1.5.AppImage`
`./Open-Vector-Editor-0.1.5.AppImage`

That's it.

**Comment by tnrich** [comment]
Thanks for the instructions @beeltetun ! @daniel-westcott let me know if that works for you. If so I'll add these instructions to the readme

**Comment by daniel-westcott** [comment]
Thanks @beeltetun! It works!

**Comment by tnrich** [comment]
I've added clearer install instructions to the readme here: https://github.com/tnrich/ove-electron/blob/master/README.md#installation-instructions

@daniel-westcott and @beeltetun if either of you have a moment, I'd love to hear what you think of the tool 

Any feedback from real users is always appreciated :)

Thanks!
